-- DROP TABLE IF EXISTS TOOL;  
-- CREATE TABLE TOOLS (  
-- id INT AUTO_INCREMENT  PRIMARY KEY,  
-- tool_code VARCHAR(50) NOT NULL,  
-- tool_type INT NOT NULL,
-- brand VARCHAR(50) NOT NULL  
-- );  

DROP TABLE IF EXISTS TOOLTYPE;  
CREATE TABLE TOOLTYPE(
    id INT AUTO_INCREMENT PRIMARY KEY,
    tool_name VARCHAR(50) NOT NULL,
    daily_charge DOUBLE PRECISION NOT NULL,
    weekday_charge BOOL NOT NULL,
    weekend_charge BOOL NOT NULL,
    holiday_charge BOOL NOT NULL
);

DROP TABLE IF EXISTS TOOLS;  
CREATE TABLE TOOLS(  
id INT AUTO_INCREMENT  PRIMARY KEY,  
tool_code VARCHAR(50) NOT NULL,  
tool_type_id INT NOT NULL,
brand VARCHAR(50) NOT NULL  
);  
